Repository team-berlin/Tudee, pull requests merged in 2025-06, with the labels that each got.

#11 Feature/components priority chips
  app/src/main/java/com/example/tudee/presentation/components/PriorityChip.kt
  app/src/main/res/drawable/ic_priority_high.xml
  app/src/main/res/drawable/ic_priority_low.xml
  app/src/main/res/drawable/ic_priority_medium.xml
Labels: feature

#24 resolve compilation error in snack bar component
  app/src/main/java/com/example/tudee/presentation/components/SnackBarComponent.kt
Labels: bug

#48 Refactor/category icon mapper
  app/src/main/java/com/example/tudee/data/mapper/PredefinedCategoryMapper.kt
  app/src/main/java/com/example/tudee/presentation/screen/onboarding/OnBoardingViewModel.kt
  app/src/main/java/com/example/tudee/presentation/screen/task_screen/ui/DetailsTask.kt
  app/src/main/java/com/example/tudee/presentation/screen/task_screen/ui/TaskButtonSheet.kt
  app/src/main/java/com/example/tudee/presentation/screen/task_screen/ui/TasksScreen.kt
  app/src/main/java/com/example/tudee/presentation/utils/PredefinedCategoryMapper.kt
  app/src/test/java/com/example/tudee/data/mapper/PredefinedCategoryMapperTest.kt
Labels: enhancement

#50 refactor PriorityChip component to support dynamic corner radius and clamped text size
  app/src/main/java/com/example/tudee/presentation/components/PriorityChip.kt
Labels: enhancement
